---
title: "Homework-week-4"
author: "Ingrid Lundeen"
date: "September 28, 2016"
output: html_document
---
```{r}
#HOMEWORK:

#Create a new GitHub repository and R Project named “homework-week-4”. In your repo, #create an R Markdown file and answer the following problems. When you are done, #“knit” your R Markdown file to .html and push your .Rmd and .html files up to #GitHub for me to look at.

#Problem 1:

#Every Saturday, at the same time, a primatologist goes and sits in the forest in #the morning and listens for gibbon calls, counting the number of calls they hear in #a 2 hour window from 5am to 7am. Based on previous knowledge, she believes that the #mean number calls she will hear in that time is exactly 15. Let X represent the #appropriate Poisson random variable of the number of calls heard in each monitoring #session.


#What is the probability that she will hear more than 8 calls during any given #session?
one<- ppois(8, lambda=15, lower=FALSE)
one
```

```{r}
#What is the probability that she will hear no calls?

two2<-dpois(x=0,lambda=15)
two2
```

```r{}
#What is the probability that she will hear exactly 3 calls?
three<-dpois(x=3,lambda=15)
three
```
```{r}
#Plot the relevant Poisson mass function over the values in range 0 ≤ x ≤ 30.
four<-dpois(0:30,lambda=15)
four
```
```{r}
barplot(four, space=0, names.arg=0:30, ylab="Pr(X=x)",xlab="x", main="Probability Mass Function")
```

```{r}
#Simulate 104 results from this distribution (2 years of Saturday monitoring sessions). 

#Plot the simulated results usirng hist(); use xlim() to set the horizontal limits from 0 to 30. Compare your histogram to the shape of your mass function from above.

five<-rpois(n=104,lambda=15)
hist(five, xlim=c(0,30), ylab="Count(X=x)", xlab="x", plot=TRUE, main="Year 1 & 2 AM Call Frequency")


#The histogram of the simulated results is slightly skewed while the probability mass function is normally distributed 
```

